### ISSUE TITLE
Is this solely timer based for state transition? 

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#36]
@pietroglyph If so, it is risky in the worse case and not optimized in the best case

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L246

**Comment by binnur** [comment]
Similar reference to the following as well -- thinking using driver indicators over timers when sensors not available is would be a better way to go 

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L260

**Comment by binnur** [comment]
Note: looks like panhandling is also doing its own timer for state transition: 
https://github.com/Spartronics4915/2019-DeepSpace/blob/cb71895abe5b2d41348902613a6be83130e44a13/src/main/java/com/spartronics4915/frc2019/subsystems/PanelHandler.java#L102

**Comment by pietroglyph** [comment]
@binnur This is an interesting design question with the entire superstructure... Right now, everything is one action, but it might make sense for us to change this so that the driver presses the align button, verifies that everything is good, and then releases the panel/cargo/whatever. If we stick with what we have, the timers are probably necessities.

**Comment by binnur** [comment]
K - test well as the human perception of time and expectation needs to be set here w/ Cruz & Chris.
